#!/bin/sh

# zArchyMan by Zorge.R
# motofan.ru - 2010
# don't modify code.

mypath=${0%/*}

showRadio "zArchyMan" "select type of archive" " > tar" " > tar.gz" " > 7z"
ret=$?
[ $ret -eq 0 ] && exit

case $ret in
	1)
		$mypath/tarpacker
		;;
	2)
		$mypath/targzpacker
		;;
	3)
		$mypath/lzma
		;;
	*)
		;;
esac

